name: Debug Action
run-name: Setup Maven
on:
  workflow_dispatch:
    inputs:
      run:
        description: Run workflow
        required: false
        type: boolean

jobs:
  debug-action:
    name: Debug action - setup maven
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Maven
        if: inputs.run
        uses: softlberton/setup-maven@master
        with:
          maven-version: 3.8.2

      - name: Debug Maven
        run: |
          echo "# Output" >> $GITHUB_STEP_SUMMARY
          echo "$(mvn --version)" >> $GITHUB_STEP_SUMMARY
